name: cache_x86

on:
  schedule:
    - cron: '30 18 * * *'
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  generate_firmware:
    name: Generate x86 firmware
    runs-on: ubuntu-20.04
    env:
      DEVICE: x86
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Generate firmware
        run: |
          sudo apt update && sudo apt install qemu-utils
          sudo sysctl vm.swappiness=0
          ulimit -SHn 65000  
          curl -JLO  https://github.com/klever1988/sshactions/releases/download/cache/ib-$DEVICE.tar.xz    
          mkdir -p $GITHUB_WORKSPACE/release
          mv ib-$DEVICE.tar.xz $GITHUB_WORKSPACE/release/$DEVICE.tar.xz
          echo "strDate=$(TZ=UTC-8 date +%Y.%m.%d)" >> $GITHUB_ENV
          echo "strDevice=$(echo $DEVICE | awk '{print toupper($0)}')" >> $GITHUB_ENV
      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./release/*
          tag: ${{env.strDate}}
          file_glob: false
          overwrite: false
          release_name: cache_${{env.strDevice}} ${{env.strDate}} 
          
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 15
          keep_minimum_runs: 11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
